- name: ConfigureDocker
  hosts: web
  tasks:
        - name: Docker Repo
          yum_repository:
                  name: Docker
                  description: repo4
                  baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
                  gpgcheck: no

        - name: install
          package:
                  name:
                          - "docker-ce-18.09.1-3.el7.x86_64"
                  state: present

        - name: Service of Docker
          service:
                 name: "docker"
                 state: started
                 enabled: yes

        - name: Docker Install SDK
          command: "pip3 install docker"

        - name: create a file on manage node
          file:
                  path: "/myfile"
                  state: directory

        - name: copy file from local to manage node
          copy:
               src: "/root/home.html"
               dest: "/myfile/"



        - name: Create a Docker Container
          docker_container:
              name: MyCont1
              image: httpd
              state: started
              exposed_ports:
                - "80"
              ports:
                - "8888:80"
              volumes:
                - /myfile:/usr/local/apache2/htdocs/
